export const modelHV = (data,selectedOptions,camposAdicionales,camposAdicionalesAccesorios ) => {
    return {
        version: data.version,
        fechaElaboracion: data.fechaElaboracion,
        lote: data.lote,
        inventario: data.inventario,
        nombreEquipo: data.nombreEquipo,
        marca: data.marca,
        fabricante: data.fabricante,
        modelo: data.modelo,
        equipo: selectedOptions.equipo,
        lineaProducto: data.lineaProducto,
        ubicacion: data.ubicacion,
        responsableEquipo: data.responsableEquipo,
        estadoEquipo: selectedOptions.estadoEquipo,
        registroSanitario: data.registroSanitario,
        usoEquipo: data.usoEquipo,
        imagenesEquipo: data.imagenesEquipo ? URL.createObjectURL(data.imagenesEquipo[0]) : null,
        imagenesFirma: data.imagenesFirma ? URL.createObjectURL(data.imagenesFirma[0]) : null,
        temperatura: data.temperatura,
        humedad: data.humedad,
        altitud: data.altitud,
        alto: data.alto,
        ancho: data.ancho,
        profundidad: data.profundidad,
        peso: data.peso,
        voltaje: data.voltaje,
        potencia: data.potencia,
        corriente: data.corriente,
        frecuencia: data.frecuencia,
        fuente: data.fuente,
        rangoVoltaje: data.rangoVoltaje,
        rangoPotencia: data.rangoPotencia,
        rangoPresion: data.rangoPresion,
        rangoHumedad: data.rangoHumedad,
        rangoCorriente: data.rangoCorriente,
        frecuenciaTecMant: data.frecuenciaTecMant,
        rangoVelocidad: data.rangoVelocidad,
        pesoTecMant: data.pesoTecMant,
        rangoTemperaturaTecMant: data.rangoTemperaturaTecMant,
        accionamiento: data.accionamiento,
        recomendacionesFabricante: data.recomendacionesFabricante,
        operacion: data.operacion,
        mantenimiento: data.mantenimiento,
        instalacion: data.instalacion,
        otrosRegTEc: data.otrosRegTEc,
        planos: selectedOptions.planos,
        guiaManejo: selectedOptions.guiaManejo,
        fechaAdquision: data.fechaAdquision,
        tiempoGarantia: data.tiempoGarantia,
        frecuenciaMantenimiento: selectedOptions.frecuenciaMantenimiento,
        clasificacionRiesgo: selectedOptions.clasificacionRiesgo,
        otrasRecTec: data.otrasRecTec,
        preventivoSi: data.preventivoSi ? data.preventivoSi : "No",  // <-- Procesa el valor aquí
        preventivoPropio: data.preventivoPropio,
        preventivoNo: data.preventivoNo,
        preventivoTercerizado: data.preventivoTercerizado,
        preventivoNota: data.preventivoNota,
        correctivoSi: data.correctivoSi,
        correctivoPropio: data.correctivoPropio,
        correctivoNo: data.correctivoNo,
        correctivoTercerizado: data.correctivoTercerizado,
        correctivoNota: data.correctivoNota,
        calibracionSi: data.calibracionSi,
        calibracionPropio: data.calibracionPropio,
        calibracionNo: data.calibracionNo,
        calibracionTercerizado: data.calibracionTercerizado,
        calibracionNota: data.calibracionNota,
        componentes: camposAdicionales.map((campo, index) => ({
          nombre: data[`nombreParte${index}`],
          marca: data[`marcaParte${index}`],
          modelo: data[`modeloParte${index}`],
          referencia: data[`referenciaParte${index}`],
          serial: data[`serialParte${index}`],
          cantidad: data[`c${index}`],
        })),
        // Campos de accesorios
        accesorios: camposAdicionalesAccesorios.map((campo, index) => ({
          nombre: data[`nombreAccesorio${index}`],
          marca: data[`marcaAccesorio${index}`],
          modelo: data[`modeloAccesorio${index}`],
          referencia: data[`referenciaAccesorio${index}`],
          serial: data[`serialAccesorio${index}`],
          cantidad: data[`ca${index}`],
        })),
        fechaFinal: data.fechaFinal,
        observacionesFinal: data.observacionesFinal,
      };
}