export const modelRS = (data,selectedOptions,camposAdicionales,camposAdicionalesR ) => {

    return {
        version: data.version,
        fechaElaboracion: data.fechaElaboracion,
        fechaReporte: data.fechaReporte,
        reporteTecnico: data.reporteTecnico,
        numeroTelefono: data.numeroTelefono,
        direccionLogistica: data.direccionLogistica,
        ciudadDepartamento: data.ciudadDepartamento,
        nombreEquipo: data.nombreEquipo,
        nombreMarca: data.nombreMarca,
        nombreReferencia: data.nombreReferencia,
        nombreModelo: data.nombreModelo,
        nombreSerial: data.nombreSerial,
        numeroInventario: data.numeroInventario,
        lineaProducto: data.lineaProducto,
        ubicacionCirugia: data.ubicacionCirugia,
        nombreMantenimiento: data.nombreMantenimiento,
        telefonoMantenimiento: data.telefonoMantenimiento,
        cargoMantenimiento: data.cargoMantenimiento,
        correoMantenimiento: data.correoMantenimiento,
        descontaminacion: selectedOptions.descontaminacion,
        carcaza: selectedOptions.carcaza,
        accesorios: selectedOptions.accesorios,
        conectores: selectedOptions.conectores,
        interruptores: selectedOptions.interruptores,
        indicadores: selectedOptions.indicadores,
        cargadores: selectedOptions.cargadores,
        sistemaElectrico: selectedOptions.sistemaElectrico,
        sistemaElectronico: selectedOptions.sistemaElectronico,
        medicion: selectedOptions.medicion,
        empaques: selectedOptions.empaques,
        nivelesAlarma: selectedOptions.nivelesAlarma,
        otros: selectedOptions.otros,
        nombreEntrego: data.nombreEntrego,
        cedulaEntrego: data.cedulaEntrego,
        cargoEntrego: data.cargoEntrego,
        FirmaEntrego: data.FirmaEntrego,
        nombreRecibio: data.nombreRecibio,
        cedulaRecibio: data.cedulaRecibio,
        cargoRecibio: data.cargoRecibio,
        FirmaRecibio: data.FirmaRecibio,
        fechaInicio: data.fechaInicio,
        fechaFinalizacion: data.fechaFinalizacion,
        mantenimientoSelect: selectedOptions.mantenimientoSelect,
        mantenimiento: camposAdicionales.map((campo, index) => ({
          pruebaFalla: data[`pruebaFalla${index}`],
          descripcionMantenimiento: data[`descripcionMantenimiento${index}`],
          observacionesMantenimiento: data[`observacionesMantenimiento${index}`],
        })),
        pR: selectedOptions.pR,
        eFQ: selectedOptions.eFQ,
        repuestosRequeridos: camposAdicionalesR.map((campo, index) => ({
          cantidadRepuestos: data[`cantidadRepuestos${index}`],
          descripcionRepuestos: data[`descripcionRepuestos${index}`],
          referenciaRepuestos: data[`referenciaRepuestos${index}`],
        })),
        notaRepuestos: data.notaRepuestos,
        recomendacionesUso: data.recomendacionesUso,
        observacionesFinales: data.observacionesFinales,
        nombreResponsable: data.nombreResponsable,
        numeroRecursoHumano: data.numeroRecursoHumano,
        cargoResponsable: data.cargoResponsable,
        FirmaReponsable: data.FirmaReponsable,
      };
  
}